import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "MD Waleedul Haque | MERN Stack & AI Developer",
  description: "MD Waleedul Haque's professional portfolio - Computer Science Engineering student specializing in MERN Stack Development and AI/ML. Building scalable solutions for EdTech, streaming, and social platforms.",
  keywords: [
    "mern-stack",
    "full-stack-developer",
    "ai-ml-engineer",
    "reactjs",
    "nextjs",
    "nodejs",
    "mongodb",
    "express",
    "firebase",
    "python",
    "machine-learning",
    "tensorflow",
    "scikit-learn",
    "portfolio",
    "computer-science",
    "web-development",
    "javascript",
    "typescript",
    "tailwindcss",
    "docker",
    "aws",
    "vercel",
    "git",
    "mysql",
    "supabase",
    "webrtc",
    "streaming",
    "edtech",
    "social-platform",
  ] as Array<string>,
  authors: {
    name: "MD Waleedul Haque",
    url: "https://github.com/waleedul3",
  },
} as const;
